version: "3.8"

volumes:
 data:

networks:
  local-euc:
    name: local-euc

services:
  nginx:
    container_name: nginx
    image: nginx:1.17.2
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/key.cer:/root/key.cer
      - ./nginx/cert.pem:/root/cert.pem
    ports:
      - "80:80"
    networks:
      - local-euc
    command: [nginx-debug, "-g", "daemon off;"]
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    hostname: euc_db
    container_name: euc_db
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sql
      - POSTGRES_PORT=5432
      - POSTGRES_DB=euc_data
    networks:
      - local-euc
  bokeh:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: bokeh
    networks:
      - local-euc
    