Filename: nrsa-fish-tissue-study-pcb-data-9-30-14.xlsx
Type: xlsx
Sheet: 'NRSA 2008 PCB Data'

tables: 
  samples:
    sqlalchemy_obj: Sample
    keys: [ EPA_SAMPLE_ID, PARAMETER_NAME ]
    columns: 
      EPA_SAMPLE_ID: "EPA Sample ID"
      SITE_ID: "Site ID"
      PERCENT_LIPIDS: "% Lipids"
      PARAMETER_NAME: Analyte
      CAS_NO: "CAS Number"
      PARAMETER_CATEGORY: Class
      AMOUNT: Amount
      AMOUNT_UNITS: "Unit 1"
      MDL: MDL
      METHOD: Method
      QL: QL
      COMMENTS: Comments


