Filename: /Users/arnsong/Dropbox (Dartmouth College)/RC_EUCs_cchen/EUCs/EUC2/NRSA/pcb-data-2013-2014.xlsx
Type: xlsx
Sheet: '2013-14 NRSA PCB Data'

tables: 
  samples:
    sqlalchemy_obj: Sample
    keys: [ EPA_SAMPLE_ID, PARAMETER_NAME ]
    columns: 
      EPA_SAMPLE_ID: EPA Sample ID
      SITE_ID: Site ID
      TISSUE_TYPE: Tissue Type
      PERCENT_LIPIDS: '% Lipids'
      PARAMETER_NAME: Chemical
      CAS_NO: CAS Number
      AMOUNT: Amount
      AMOUNT_UNITS: Unit 1
      MDL: MDL
      METHOD: Method
      QL: QL
      COMMENTS: Comments


